/* Keyboard accelerators, shared by main.ts (app-level, for menu accel labels)
 * and window.ts (an explicit bubble-phase Gtk.ShortcutController that reliably
 * triggers the actions — app-level accels alone weren't firing under node-gtk).
 * Bubble phase means a focused text entry still gets Ctrl+C/V/A for its text. */
export const ACCELS: Record<string, string[]> = {
  'win.back': ['<alt>Left'],
  'win.forward': ['<alt>Right'],
  'win.up': ['<alt>Up'],
  'win.go-home': ['<alt>Home'],
  'win.reload': ['<ctrl>r', 'F5'],
  'win.new-tab': ['<ctrl>t'],
  'win.new-window': ['<ctrl>n'],
  'win.toggle-split': ['F3'],
  'win.focus-other-pane': ['F6'],
  'win.close-tab': ['<ctrl>w'],
  'win.tab-prev': ['<ctrl>Page_Up'],
  'win.tab-next': ['<ctrl>Page_Down'],
  'win.location': ['<ctrl>l'],
  'win.search': ['<ctrl>f'],
  'win.show-hidden': ['<ctrl>h'],
  'win.select-all': ['<ctrl>a'],
  'win.invert-selection': ['<ctrl><shift>i'],
  'win.copy': ['<ctrl>c'],
  'win.cut': ['<ctrl>x'],
  'win.paste': ['<ctrl>v'],
  'win.undo': ['<ctrl>z'],
  'win.redo': ['<ctrl><shift>z'],
  'win.open-new-tab': ['<ctrl>Return'],
  'win.rename': ['F2'],
  'win.create-link': ['<ctrl>m'],
  'win.trash': ['Delete'],
  'win.delete': ['<shift>Delete'],
  'win.new-folder': ['<ctrl><shift>n'],
  'win.view-list': ['<ctrl>1'],
  'win.view-grid': ['<ctrl>2'],
  'win.zoom-in': ['<ctrl>plus', '<ctrl>equal'],
  'win.zoom-out': ['<ctrl>minus'],
  'win.zoom-reset': ['<ctrl>0'],
  'win.properties': ['<ctrl>i', '<alt>Return'],
  'win.preferences': ['<ctrl>comma'],
  'win.shortcuts': ['<ctrl>question', '<ctrl>slash'],
  'win.quit': ['<ctrl>q'],
}
